name: DonutShop
version: 1.0-SNAPSHOT
main: devs.donutShop.DonutShop
api-version: '1.21'
softdepend: [Vault]
commands:
  shop:
    description: Opens the Shop menu
    aliases: [buy, quickbuy, qb]
permissions:
  donutshop.admin:
    description: Edit isi Shop (tambah, ubah, hapus item)
    default: op
